### ISSUE TITLE
Unable to generate Access token

### ISSUE THREAD

**Issue by damianavid** [microsoft/playwright-testing-service#102]
**Describe the bug**
Unable to generate Access token in Microsoft Playwright Testing dashboard.

**To Reproduce**
1. Step 1 'Following the setup guide'
2. Step 2 'Click the cog icon in header, under settings select Access tokens. Click the 'Generate new token' button and fill out the form.'
4. See error - undefined is not an object (evaluating 'r.error')

**Expected behavior**
Generate an Access token.

**Screenshots**
<img width="1470" alt="Screenshot 2024-03-27 at 12 13 14 PM" src="https://github.com/microsoft/playwright-testing-service/assets/104377410/0c263476-f129-489d-903c-d10c3282ba40">
<img width="1470" alt="Screenshot 2024-03-27 at 12 15 37 PM" src="https://github.com/microsoft/playwright-testing-service/assets/104377410/56321fc4-5009-46af-a763-9bde6fca10e6">
<img width="1470" alt="Screenshot 2024-03-27 at 12 15 43 PM" src="https://github.com/microsoft/playwright-testing-service/assets/104377410/cc55ca90-7653-4e5b-88e4-7f55d58966e2">
<img width="1470" alt="Screenshot 2024-03-28 at 1 03 45 PM" src="https://github.com/microsoft/playwright-testing-service/assets/104377410/ceb7ce28-16d4-4713-afd3-dc63f533a2ce">
<img width="1470" alt="Screenshot 2024-03-28 at 1 03 52 PM" src="https://github.com/microsoft/playwright-testing-service/assets/104377410/19cca5b1-b7c3-4615-b54a-061debbdfb87">
<img width="1470" alt="Screenshot 2024-03-28 at 2 15 09 PM" src="https://github.com/microsoft/playwright-testing-service/assets/104377410/68cc1103-c1ed-4d02-8533-fb915a0b6b98">
<img width="1470" alt="Screenshot 2024-03-28 at 2 15 23 PM" src="https://github.com/microsoft/playwright-testing-service/assets/104377410/7a336ebb-7684-469e-9498-06d0901a0346">
<img width="1470" alt="Screenshot 2024-03-28 at 2 16 32 PM" src="https://github.com/microsoft/playwright-testing-service/assets/104377410/2d498fad-35c2-4f56-86a5-38749de9b801">

**Setup information (please complete the following information):**
 - Azure Subscription Id: 8f9290f9-f4dc-4be5-83e2-3c831b8d66ee
 - Workspace Name: uicoe
 - Service trace Id (if available): N/A
 - Log snippet (if available): Log screenshots above
 - Browser on which tests are executed (if applicable): Safari Version 16.6 + Chrome Version 123.0.6312.86
 - Time range (in PST) when the issue was experienced: 03/25 - 03/29 9:00am - 5:00pm PST
 - Playwright Version: "@nx/playwright": "16.7.4", "@playwright/test": "^1.36.0", "eslint-plugin-playwright": "^0.15.3",
- Client machine OS: MacBook Air M2 Ventura 13.6.3
- OS requested on Service: N/A

**Additional context**

AB#2017176

**Comment by puagarwa** [comment]
Hi @damianavid,
    We looked into har file which you shared offline. we observed one strange thing in har request about remote address being set as :80, ideally it should be our remote address which is something like this [2620:1ec:bdf::72]:443,

Can you please try these options
- Try from different machine and network, you could also try it from your phone 
- check if there is any configuration at your side intercepting requests, you may need to allow our domains. 

snippet from har file
![image](https://github.com/microsoft/playwright-testing-service/assets/28705989/dd537dc4-bfeb-4f93-a304-03614f8dbfd8)

**Comment by damianavid** [comment]
Hi Puneet,

I tried it on my phone and 5G network instead of my personal WIFI and still encountering the same issue. I also have coworkers in different states on different machines and networks that are encountering the same issue. I don’t have a proxy or anything set on my end so there is no configuration on my end intercepting requests.

Could this be an issue in the code that is making this request? Not sure what else to try

From: Puneet Agarwal ***@***.***>
Date: Tuesday, April 2, 2024 at 5:45 AM
To: microsoft/playwright-testing-service ***@***.***>
Cc: Damian Ruiz ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/playwright-testing-service] Unable to generate Access token (Issue #102)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Caution: This email originated outside of AvidXchange. Do not click links or open attachments unless you recognize the sender and know the content is safe. Please use the Report Phish button to forward any suspicious message to Information Security.


Hi @damianavid<https://github.com/damianavid>,
We looked into har file which you shared offline. we observed one strange thing in har request about remote address being set as :80, ideally it should be our remote address which is something like this [2620:1ec:bdf::72]:443,

Can you please try these options

  *   Try from different machine and network, you could also try it from your phone
  *   check if there is any configuration at your side intercepting requests, you may need to allow our domains.

snippet from har file
image.png (view on web)<https://github.com/microsoft/playwright-testing-service/assets/28705989/dd537dc4-bfeb-4f93-a304-03614f8dbfd8>

**Comment by puagarwa** [comment]
Hi @damianavid ,
    Sure that rules out your network or machine issue. Can you please help collect har file with preserve log option ticket and share all logs from the time you login on portal and then try creating token. please send log on email alias.

**Comment by puagarwa** [comment]
Hi @damianavid ,
    We have made a probable fix, can you please try now and if it doesnt work send us har file with preserve logs.

**Comment by damianavid** [comment]
Hi Puneet,

It is now working on my end as expected so looks like the fix went through. Thank you for your help on this!

From: Puneet Agarwal ***@***.***>
Date: Thursday, April 4, 2024 at 6:02 AM
To: microsoft/playwright-testing-service ***@***.***>
Cc: Damian Ruiz ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/playwright-testing-service] Unable to generate Access token (Issue #102)
Caution: This email originated outside of AvidXchange. Do not click links or open attachments unless you recognize the sender and know the content is safe. Please use the Report Phish button to forward any suspicious message to Information Security.


Hi @damianavid<https://github.com/damianavid> ,
We have made a probable fix, can you please try now and if it doesnt work send us har file with preserve logs.

**Comment by puagarwa** [comment]
thanks for confirming the fix. feel free to open new issue if you face any issue or have any question for us while using the service.
