### ISSUE TITLE
[BUG]:[Getting certificate error while connecting to playwright service]

### ISSUE THREAD

**Issue by sgollapa** [microsoft/playwright-testing-service#104]
**Describe the bug**
I have provided my access token and added region endpoint in the setup. Now when I am executing the test to connect to playwright service, its throwing a certificate error.

**To Reproduce**
1. create playwright.service.config.ts
2. create .env file
3. provide access token generated from playwright service and add region end point url in the .env
4. Run "npx playwright test --config=playwright.service.config.ts --workers=2"

**Expected behavior**
Playwright tests should be executed and playwright service should be connected with test results displayed in playwright service.

**Screenshots**

**Setup information (please complete the following information):**
 - Azure Subscription Id:
 - Workspace Name:
 - Service trace Id (if available):
 - Log snippet (if available):
 - Browser on which tests are executed (if applicable):
 - Time range (in PST) when the issue was experienced:
 - Playwright Version:
- Client machine OS:
- OS requested on Service:

**Additional context**

**Comment by puagarwa** [comment]
Hi , can you please provide below information 
Subscription id: 
Error message and/or stacktrace

**Comment by sgollapa** [comment]
> Hi , can you please provide below information Subscription id: Error message and/or stacktrace
Hi Puneet,
tried attaching the screenshot but failed. please find below the details:
Subscription id: b060cfe5-9862-43e2-b7dd-de2d40ea480b

error: 
npx playwright test --config=playwright.service.config.ts --workers=2

Running 2 tests using 2 workers
  1) [chromium] › example.spec.ts:10:5 › get started link ──────────────────────────────────────────

    Error: browserType.connect: WebSocket error: unable to get local issuer certificate
    Call log:
      - <ws connecting> wss://eastasia.api.playwright.microsoft.com/api/authorize/connectSession
      - <ws error> wss://eastasia.api.playwright.microsoft.com/api/authorize/connectSession error unable to get local issuer certificate
      - <ws connect error> wss://eastasia.api.playwright.microsoft.com/api/authorize/connectSession unable to get local issuer certificate

**Comment by puagarwa** [comment]
Hi @sgollapa,
   We verified on our service side that our SSL cert is in good shape and other customers are also able to use it. It could be some issue at your client machine or network restriction which is facing problem getting certification chain. 
 - Can you try it from another machine or another network, if you are in some corp network, problem trying it from outside of corp network would help.
 - Can you share more detail around your client machine, network.
 - BTW, if you were able to generate accessKey from our portal then it means your browser is able to work SSL properly on our server but it seems only your client from where you ran the test threw error.

**Comment by puagarwa** [comment]
HI @sgollapa ,
  One more thing, if above suggestion didnt work then please help enable debug logs via below method and share with us at our email alias 
Set environment variable
DEBUG=pw:*
DEBUG_FILE=log.log

then, send us log.log file at playwrighttesting@microsoft.com

**Comment by puagarwa** [comment]
Hi @sgollapa, If you are still facing the issue then please help us with above logs to debug the issue.

**Comment by puagarwa** [comment]
HI @sgollapa,
  Just checking if you were able to resolve the issue with your networking team. Let me know if you need any help.

**Comment by sgollapa** [comment]
Hi @puagarwa ,
This issue is resolved from the jumphost and issue testing it from local network is still pending. This issue can be closed currently as there is a wait time to check the issue in local. I shall raise further request if I need support from Microsoft.
Thank you.
