### ISSUE TITLE
[BUG]: Error: browserType.connect: WebSocket error: wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized

### ISSUE THREAD

**Issue by paradix86** [microsoft/playwright-testing-service#107]
Error: browserType.connect: WebSocket error: wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized
    Call log:
      - <ws connecting> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession
      - 1a04d19f-4e3a-40b3-bada-b4e52d696993
      - <ws unexpected response> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized
      - <ws error> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established
      - <ws connect error> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established
      - <ws disconnected> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=

**Comment by puagarwa** [comment]
HI @parafix86,
    We checked our telemetry and found the request is genuine 401 failure due to token expiry being in past 03/08/2024 07:39:54, can you please generate new token from https://playwright.microsoft.com/ and try it again.

**Comment by darshandp007** [comment]
### Getting same issue with Playwright VSCode extension

Error: browserType.connect: WebSocket error: wss://westus3.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized
Call log:
  - <ws connecting> wss://westus3.api.playwright.microsoft.com/api/authorize/connectSession
  - b1ace247-9d06-4b73-9010-70321ea10c9a
  - <ws unexpected response> wss://westus3.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized
  - <ws error> wss://westus3.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established
  - <ws connect error> wss://westus3.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established
  - <ws disconnected> wss://westus3.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=

**Comment by puagarwa** [comment]
Hi @darshandp007 , I looked into your request in your telemetry and it seems you are also hitting the genuine 401 issue because your access Key is expired (12/12/2023 04:26:51), please generate a new key by following this and try again. https://learn.microsoft.com/en-us/azure/playwright-testing/how-to-manage-access-tokens

**Comment by darshandp007** [comment]
> Hi @darshandp007 , I looked into your request in our telemetry and it seems you are also hitting the genuine 401 issue because your access Key is expired (12/12/2023 04:26:51), please generate a new key by following this and try again. https://learn.microsoft.com/en-us/azure/playwright-testing/how-to-manage-access-tokens

@puagarwa I'm using in my local not cloud service. And It was work perfectly 2 day's back.
This extension: https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright

**Comment by puagarwa** [comment]
> > Hi @darshandp007 , I looked into your request in our telemetry and it seems you are also hitting the genuine 401 issue because your access Key is expired (12/12/2023 04:26:51), please generate a new key by following this and try again. https://learn.microsoft.com/en-us/azure/playwright-testing/how-to-manage-access-tokens
> 
> @puagarwa I'm using in my local not cloud service. And It was work perfectly 2 day's back. This extension: https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright
> 
> **I think that's issue on latest(1.1.1) release of VSCode extension, It's woking fine with previous version.**

Hi @darshandp007 , Can you provide below info
Are you using MPT service ?
If yes, then please check the value of env variable PLAYWRIGHT_SERVICE_ACCESS_KEY and parse it in jwt.io and check expiry.
if this is expired, please generate a new token and try it.

**Comment by puagarwa** [comment]
> HI @parafix86, We checked our telemetry and found the request is genuine 401 failure due to token expiry being in past 03/08/2024 07:39:54, can you please generate new token from https://playwright.microsoft.com/ and try it again. please follow this link for reference https://learn.microsoft.com/en-us/azure/playwright-testing/how-to-manage-access-tokens

HI @paradix86 , Just checking if you get chance to check with new access key.

**Comment by paradix86** [comment]
hey  @puagarwa,
Sorry for not being able before to give the feedback

Yes, that was the issue.

I honestly think that the error message can be improved, and I don't understand why if I'm running locally, playwright, if I have a playwright.service.config.ts in my project with an expired token (  PLAYWRIGHT_SERVICE_ACCESS_KEY ), you cannot even run local test. We were trying the "cloud" preview services a long time ago and honestly even forgot about that feature, but a local test must not fail for an expired token of a non-used service.

Is there already a feature request or bug opened about that?

**Comment by puagarwa** [comment]
HI @paradix86 ,  Our service usage is irrespective of local vs CI agent, customers do like to use the service even when running test from local. 

However, if you are looking to control how to switch between running with service vs without service, there are two options
- You can run your test using your default playwright.config.ts file which doesnt have service integration (npx playwright test --config playwright.config.ts)
- You could as well add env variable to control the service integration toggle in service config file. like this https://github.com/microsoft/playwright-testing-service/pull/108

**Comment by puagarwa** [comment]
@paradix86 closing the issue. feel free to open issue if you need any help.
