### ISSUE TITLE
Request: info how to use a Playwright service testing a Private endpoint enabled service

### ISSUE THREAD

**Issue by kedar-1** [microsoft/playwright-testing-service#111]
**Is your feature request related to a problem? Please describe.**
Is it possible to use a Playwright Testing Service to test an app running on Azure vnet not accessible from Internet?

**Describe the solution you'd like**
A wiki page about how to use a Playwright in Vnet with Private Endpoint enabled Static Web App. 

**Describe alternatives you've considered**
Settings on playwright framework?

**Comment by vvs11** [comment]
Yes, you can run test your apps that are not pubic using Microsoft Playwright Testing. 
To do this you need to:
1. Make sure that your app is accessible from the local machine/CI machine from where you are running your tests
2. Enable 'expose-network' setting in the Playwright service config. You can read more about it [here](https://learn.microsoft.com/en-us/azure/playwright-testing/how-to-test-local-applications)

Please try these steps and let us know if you face any issues.

**Comment by vvs11** [comment]
@kedar-1 Let me know if you have any other questions

**Comment by vvs11** [comment]
@kedar-1 Closing this. Feel free to re-open if you have any issues
