### ISSUE TITLE
Quota increase request

### ISSUE THREAD

**Issue by lliang87** [microsoft/playwright-testing-service#112]
## Quota Increase Request

**Quota to Increase:**
 

[Specify which quota you would like to increase]

* [x] Maximum number of workers for the workspace
* [ ] Maximum number of workspaces per subscription
* [ ] Throttling limits
* [ ] Other

 

**Business Justification:**
We have a large number of growing e2e tests that are run automatically when PRs are made or updated. We are already encountering an error with connection timeouts to the service as mentioned in [this issue](https://github.com/microsoft/playwright-testing-service/issues/103) which we suspect is because we are hitting the current quota of 50. At the moment we have 5 (soon to be 6) projects' test suites containing an average of 28 tests running in parallel. As we have a fast and frequent turnaround of PRs we want to minimize the time taken for our e2e tests to run as they are required to complete successfully for a merge to occur, hence running all the tests in parallel. We predict that each project's test suite will grow to about an average of 50 tests in which case each run would need about 250 workers in parallel to accommodate this. Additionally, since we have multiple PRs active at a time this could mean 3 - 4 runs simultaneously which is why we are requesting for significantly more workers.

**Requested New Quota Limit:**
We would like to request for 1000 workers per workspace.

**Additional Information:**

[Include any additional information that may be relevant to your request, such as project deadlines, the impact of the quota increase on your work, etc.]

**Setup Information:**

- **Subscription ID:** dedcf506-642c-410a-b4ab-7d9a05ae3fbf
- **Workspace ID:** westus3_d65416cb-ba18-4ec9-b069-bfe017698757

**Disclaimer:**

Please note that while we will do our best to accommodate your quota extension request, we may not be able to fulfill every request due to resource constraints. We will review your request and provide a response as soon as possible.

**Comment by vvs11** [comment]
Hi @lliang87
Thanks for raising this request. We are working through our systems to accommodate this request. Meanwhile, can we set up a call to understand more about how you are using the service and your experience with it? Your feedback will help us improve the product. 
Please send us an email to playwrighttesting@microsoft.com and I will send you a meeting invite. 
Thanks

**Comment by vvs11** [comment]
Hi @lliang87, 
We have increased the quota for your workspace to 250. Please try it out along with other solutions we discussed. 
You can also go through this doc: https://learn.microsoft.com/en-us/azure/playwright-testing/concept-determine-optimal-configuration to understand more about how to optimize your test suite.

**Comment by lliang87** [comment]
Hey @vvs11 ,
Thanks for that, we will try it out with more workers now and see how it goes. 
Also, is there a reason why we were not able to get the requested quota of 1000 but only 250?

**Comment by vvs11** [comment]
@lliang87 We have increased to 250 right now based on the requirements of your test suite. You can try to optimize your test suite based on the documentation shares. If you need more, please reach out to us, we can increase it further. 
Also, we have introduced reporting capability which is currently in invite-only preview. Please check out the announcement here: https://aka.ms/mpt/reporting-announce

**Comment by vvs11** [comment]
Closing this, since the quota is increased. Please reach out if you want to increase it further
