### ISSUE TITLE
Add annotations with scroll

### ISSUE THREAD

**Issue by apis3445** [microsoft/playwright-testing-service#113]
**Is your feature request related to a problem? Please describe.**
I am adding annotations to generate human-readable test steps. This is one sample

![image](https://github.com/microsoft/playwright-testing-service/assets/7475390/79306da5-f9e6-4322-81e0-1dc14fd7d1fa)

The annotations in the report show all in one row, and some are overlapped
![image](https://github.com/microsoft/playwright-testing-service/assets/7475390/02e4fc46-f520-4288-a082-d4b5976014ba)

**Describe the solution you'd like**
Add the same design for annotations in the HTML reporter to the playwright service reporting

**Describe alternatives you've considered**

**Additional context**

**Comment by vvs11** [comment]
Thanks @apis3445 for raising this. We will work on this and fix it soon

**Comment by vvs11** [comment]
@apis3445, this is fixed. Could you check and verify?

**Comment by apis3445** [comment]
Hi! It is working, thank you. Adds the scrollbar to the long text, not to the bar, but is ok
![image](https://github.com/user-attachments/assets/c3ace8a9-86c7-4b5d-ad5c-32f51c877a28)

**Comment by vvs11** [comment]
Thanks for the confirmation. Please reach out to us if you need anything else
