### ISSUE TITLE
[BUG]:Quickstart Docs Typo for ADO Pipeline Example

### ISSUE THREAD

**Issue by PagelsR** [microsoft/playwright-testing-service#115]
**Describe the bug**
Documentation type at section "Enable test results reporting"

https://learn.microsoft.com/en-us/azure/playwright-testing/quickstart-automate-end-to-end-testing?tabs=pipelines#enable-test-results-reporting

"Update the CI workflow definition to install the reporting package"

Typo for the **Azure Pipelines example code**.
Script should read like this:

Change this,

'npm set //npm.pkg.github.com/:_authToken **${{secrets PAT_TOKEN_PACKAGE}}**'

to this,

'npm set //npm.pkg.github.com/:_authToken **${PAT_TOKEN_PACKAGE}**'

**Comment by vvs11** [comment]
Thanks for reporting this. We will fix it in the docs asap.

**Comment by vvs11** [comment]
This is fixed
