### ISSUE TITLE
Intermittent test failures due to timeout with Chromium on Playwright 1.45 

### ISSUE THREAD

**Issue by vvs11** [microsoft/playwright-testing-service#117]
We are seeing some intermittent issues with tests running on Playwright 1.45 Chromium browser. 
The test gets stuck and fails with a timeout error. 
We are diagnosing the issue and will share an update soon. 

If you are facing this issue, please downgrade to Playwright 1.44.  

Sample Error messages
Error: browserContext.newPage: Test timeout of 300000ms exceeded

**Comment by puagarwa** [comment]
This issue fixed, it was regression in playwright chromium headless mode.
