### ISSUE TITLE
[BUG]:[Pipeline stuck in "in Progress" for multiple runs]

### ISSUE THREAD

**Issue by garg-shubham** [microsoft/playwright-testing-service#118]
**Describe the bug**
Here's the Test Runs page for our workspace: https://playwright.microsoft.com/workspaces/westus3_8bb7536e-c5d5-431c-9d36-89641b40423d
Pipeline link: https://dev.azure.com/msazure/One/_build?definitionId=357939&_a=summary
as you would see, there are mutiple test runs that are stuck i inProgress for days. The issue is Cloud agnostic, as the runs stuck are from different clouds. The pipeline starts 5 test runs in the night automatically to test the changes from last day. 

**Expected behavior**
Test runs should get completed / give a failed to run tests error. 

**Screenshots**
![image](https://github.com/user-attachments/assets/786dd71c-4819-43e0-a6e6-2eca0bd6eb1a)
![image](https://github.com/user-attachments/assets/e01df50b-ef47-4c29-9d0a-8740541d7fcc)

**Setup information (please complete the following information):**
 - Azure Subscription Id:55fa0fb2-a6d7-4970-9357-8a3f486994ed
 - Workspace Name: westus3_8bb7536e-c5d5-431c-9d36-89641b40423d
 - Service trace Id (if available):
 - Log snippet (if available):
 - Browser on which tests are executed (if applicable):
 - Time range (in PST) when the issue was experienced:
 - Playwright Version:
- Client machine OS:
- OS requested on Service:

**Additional context**

**Comment by pratiksharma23** [comment]
The runs were stuck in running state due to no testRun end event arriving from the client side.
This seems to be due to failing SAS token calls from the service, which exited the process.

This is mitigated by upgrading to the latest package version, as confirmed by the team.
