### ISSUE TITLE
Example of running Playwright as a library

### ISSUE THREAD

**Issue by jonathanong** [microsoft/playwright-testing-service#123]
The example provided is only for running tests via CLI. How can I run Playwright as a library? Or is that not supported?

**Comment by puagarwa** [comment]
Hi @jonathanong , I assume you mean you want to integerate MPT service with just playwright library? if yes, please follow this example https://github.com/microsoft/playwright-testing-service/issues/70.

BTW, Can you help us know your scenario ?

**Comment by jonathanong** [comment]
perfect, thank you! I am just looking for more granular control over how they are run

**Comment by puagarwa** [comment]
Sure, let me know if you need further help in your scenario.
