### ISSUE TITLE
Reporting preview?

### ISSUE THREAD

**Issue by dmcweeney** [microsoft/playwright-testing-service#124]
Hi,

We signed up for the reporting preview maybe 6 or 8 weeks ago and haven't heard anything back yet.
Juist wondering when we can expect to heard something.

Thanks,

Donal

**Comment by vvs11** [comment]
Hi @dmcweeney 
Thanks for writing to us and apologies for the delay. In your response in the sign-up form, you have indicated that you are using @microsoft scope in your project. Unfortunately, the package to enable reporting is currently private with @microsoft scope. This causes a conflict in the project and does not allow you to install it. This is the reason we could not onboard you.

We are working on mitigating it and will share an update soon on this. Thank you for your patience.

**Comment by dmcweeney** [comment]
Hi @vvs11 ,

I dont even remember that question on the signup form - I just checked the signup form again now and I dont see it? 
Can you jog my memory please! 

Thanks, Donal

**Comment by dmcweeney** [comment]
Hi @vvs11 ,

just FYI totally unrelated but getting the following error when I created or responded to this thread:

Sync issue to Azure DevOps work item: All jobs have failed

Set values from payload & env
Check to see if work item already exists
Error: Connecting to organization. Check the spelling of the organization name and ensure your token is scoped correctly.
Error: Error: Failed request: (401)
Work item value is -1, exiting action

**Comment by vvs11** [comment]
Hi @dmcweeney 
There is logic on the question, if you select the test runner as playwright/test (Q4), you will see the question. For the other error you mentioned, it is a workflow that we are using to create an internal item for us to track. 
If you want, we can onboard you and you can try the service, but you may see issues in installing the package.

**Comment by dmcweeney** [comment]
Hi @vvs11,

We use a number of @azure packages:

```
    "@azure/identity": "^4.1.0",
    "@azure/identity-vscode": "1.0.1-alpha.20240415.1",
    "@azure/keyvault-secrets": "^4.8.0",
    "@azure/msal-browser": "^3.13.0",
    "@azure/msal-node": "^2.7.0",
```

The only @microsoft package we use is:

`    "@microsoft/eslint-plugin-power-apps": "^0.2.10",
`

> If you want, we can onboard you and you can try the service, but you may see issues in installing the package

Nothing to lose!

**Comment by vvs11** [comment]
I have initiated the process for subscription onboarding. Will let you know as soon as it's done

**Comment by vvs11** [comment]
Your subscription has been onboarded and I have sent instructions. Please let us know if you need any help with onboarding

**Comment by dmcweeney** [comment]
Hi @vvs11 

Thanks. Still waiting for access to the github repo - I presume that will take some time to trickle through.

Thanks, Donal

**Comment by dmcweeney** [comment]
@vvs11 I'm in but some issues which I will log in the other repo...

**Comment by saikiran40cs** [comment]
Even we have the same issue so that we can evaluate the tool for our project

**Comment by vvs11** [comment]
Reporting feature is now public. You can read more about it here: https://aka.ms/mpt/reporting-announce-blog
