### ISSUE TITLE
[BUG]: Test Runs taking too long in the service

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright-testing-service#125]
**Describe the bug**
Hi guys, just notice some of the builds are taking too long in the service, while in the pipelines they still show as completed in minutes. It's intermittent, so just wondering if you can't take a look from your side to see if there is any errors or if that's something with the suit itself?

Attached you can see some screenshots, most of the time it takes between 3 - 5 minutes, but there are some runs showing 30min, even an hour.

Thank you

**Screenshots**
![image (1)](https://github.com/user-attachments/assets/7fcb1ffa-30ca-40ce-b3ba-4b82a3768960)
![image](https://github.com/user-attachments/assets/a55da5df-ae99-4a85-9f3b-7ad41a0269ff)

**Setup information (please complete the following information):**
 - Azure Subscription Id: 84344572-b6bc-4ab1-87d5-bbdd214cfdac
 
 - Workspace Name: AcquisitionWorkspace
 
 - Browser on which tests are executed (if applicable): Chrome
 
- Playwright Version: 1.37
 
- Client machine OS: Windows

- OS requested on Service: Linux

**Comment by puagarwa** [comment]
@imartinflores checking, will update shortly. meanwhile please check trace once to see if your test suite has regression which is holding the test for too long.

**Comment by puagarwa** [comment]
HI @imartinflores , Did you find anything on your side. Are you still facing this issue.

**Comment by imartinflores** [comment]
Hi @puagarwa ! I'm very sorry for the delay, I lost track of it. I could not see it again, but unfortunately, I could not find any logs from those runs. We're u able to see something on your side? Otherwise, feel free to close it, I'll re open it if I see that happening again!

**Comment by puagarwa** [comment]
I checked on our side but couldnt find anything alarming, closing it for.
