### ISSUE TITLE
[BUG]: Getting a 500 when execution finishes

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright-testing-service#129]
**Describe the bug**

I'm getting a `1. An unexpected error occurred on our server. Our team is working to resolve the issue. Please try again later, or contact support if the problem continues.` after I run the demo from this repo.
I bet it's a 500

**To Reproduce**
1. Download repo
2. Run tests with my credentials

**Expected behavior**
It should work?

**Setup information (please complete the following information):**
 - Azure Subscription Id: c5df64ec-39f7-4965-9192-365328414f2b
 - Workspace Name: westeurope_32dd4eb0-69ff-46d8-b35a-be3859272fca
 - Playwright Version: 1.47
- Client machine OS: MacOS

**Comment by kblok** [comment]
I created a new workspace and it started working. Maybe I should have got a better error?
Feel free to close it.

**Comment by abranj19** [comment]
Thanks for reporting this.  We have looked into the issue and fixed it and now it should give more meaningful error. Hope you are able to use the new Reporting feature. Please feel to open if you face this again.
