### ISSUE TITLE
[BUG]: If git is used in the project the playwright-testing reporter use the last git commit as title instead of the default value.

### ISSUE THREAD

**Issue by Kranael** [microsoft/playwright-testing-service#130]
**Describe the bug**
Playwright-testing-service will use ![Snag_845ea47](https://github.com/user-attachments/assets/3b3b678d-1d02-4750-a716-c232f2e19997)

So an title like 7d4504f0-b30e-4c43-acac-38341ac217f5 is generated for the reports in azure.
But under some conditions it will use the last commit as title.

**To Reproduce**

1. Step 1 'init playwright'
2. Step 2 'use azure playwright reporter'
3. Step 3 'init git'

**Expected behavior**
An title like 7d4504f0-b30e-4c43-acac-38341ac217f5 is generated

**Actual behavior**
An title like [last commit] is generated

**Screenshots**
![Snag_90e962a](https://github.com/user-attachments/assets/4503a826-9a03-4564-9bcd-a3b0d3b362c5)
![Snag_90f9386](https://github.com/user-attachments/assets/e48db5fc-0bdb-4460-b991-31c80770f6f9)

**Setup information (please complete the following information):**
 - Azure Subscription Id: /
 - Workspace Name: AutomationTestLab
 - Playwright Version: 1.47.2
- Client machine OS: Windows 11 Enterprise
- OS requested on Service: Linux
- @azure/microsoft-playwright-testing: 1.0.0-beta.3

**Additional context**
Reproducible

**Comment by vvs11** [comment]
Hi @Kranael 
Thanks for writing to us. There are two fields that are used here. Display name (title), that you see on the UI and Run ID. 
RunID is the unique identifier of the run and is used to distinguish runs on the dashboard. By default, it is a random guid. You can also set the RunID yourself but then you need to make sure that it is different for each test run for results to be visible in the UI. 

Display name or title is set as the last commit message by default if the git information is available to the test run. If it is not available, then the display name is also a random guid. 

Let us know if this resolves your query. Also, let us know when you are seeing the guid and when the commit message.

**Comment by Kranael** [comment]
Hi @vvs11 

From a user perspective, why is the last commit message the default as title? That makes no sense for me or any value out of it.
It should be a random guid or the same as the runID at best. Or it should be a random id and date of run.
The commit message is not what i would expect as a user. Pls explain the value.

Thank you

**Comment by vvs11** [comment]
Our idea with this default is to make it easy for users to correlate test runs in their CI pipeline with those in the service dashboard. By visiting the dashboard, they can quickly identify failing runs and access all the context needed for troubleshooting. The last commit message will indicate changes made to the repository, along with additional details like the branch, author, and more.
A random guid does not give any information about the test run.

**Comment by cthlo** [comment]
@vvs11 In my opinion / use case,
- the Playwright test suite isn't necessarily run just once per commit
  - e.g. to continuously monitor / test our production environment
- or, the test suite may be managed in / run from a different repository (than the repo(s) of the actual application)
  - in which case, the commit may not be that useful

Hence, I think #122 would really allow us to more easily identify the origin of the test runs from the list view.

**Comment by abranj19** [comment]
Tracking this issue with #122 . So Marking this as closed
