### ISSUE TITLE
[BUG]: When 2 browser contexts are used and video recording is enabled - only one video is uploaded to testing service

### ISSUE THREAD

**Issue by AdamOakman** [microsoft/playwright-testing-service#141]
**Describe the bug**
Whenever 2 browser contexts are used in a test and video recording is enabled - only one video is uploaded to testing service

**To Reproduce**
1. Create 2 browser contexts within one test and open 2 different URLs using these contexts
2. Enable video recording in playwright config
3. Run test using Playwright Testing Service

**Expected behavior**
2 videos should be saved in testing service report

**Actual behavior**
Only 1 video is saved in testing service report

**Comment by abranj19** [comment]
@AdamOakman Thanks for reporting this issue. We will come back with resolution plan and ETA

**Comment by kashish2508** [comment]
@AdamOakman We looked into it and issue is fixed in package version >= "1.0.0-beta.5". Please try latest version and let us know If you still face any issue.
