### ISSUE TITLE
Possible to allow Playwright Testing in Network Security Group as Service Tag(?)

### ISSUE THREAD

**Issue by tlaukkanen** [microsoft/playwright-testing-service#142]
**Is your feature request related to a problem? Please describe.**
As a best practice our development environments are not open to public internet. Is there a way to allow servers that are running the Playwright Testing tests to access my web UI by using Service Tags in Network Security Groups (NSG)?

**Describe the solution you'd like**
Adding a Service Tag for Playwright Testing service so that we could allow the traffic to our web UI with inbound security rule in Network Security Group.

**Describe alternatives you've considered**
As an alternative if there would be known IP address(es) of the servers that run the tests then those could be used instead.

**Additional context**
![Image](https://github.com/user-attachments/assets/ef5880d2-0b76-44a8-8dd7-5a5ec10656c4)

**Comment by vvs11** [comment]
@tlaukkanen 
We have a list of IPs that you can allow-list in your network to use the service: https://learn.microsoft.com/en-us/azure/playwright-testing/resource-limits-quotas-capacity#outbound-ip-addresses
Alternatively, you can try using the 'exposeNetwork' field in the playwright.service.config.ts file and set it to the domain that you want to access. https://learn.microsoft.com/en-us/azure/playwright-testing/how-to-test-local-applications#configure-playwright-to-expose-local-networks the example here shows for local network but you can also set your domain. 
Let us know if this was helpful and will work for you

**Comment by tlaukkanen** [comment]
Yes, the [outbound-ip-addresses list](https://learn.microsoft.com/en-us/azure/playwright-testing/resource-limits-quotas-capacity#outbound-ip-addresses) was exactly what I was looking for, thanks! Closing the issue as that at least partly covers this need. NSG Service Tag support would still be nice at some point 🙂
