### ISSUE TITLE
Enable Reporting / Set Browser

### ISSUE THREAD

**Issue by JDCain** [microsoft/playwright-testing-service#145]
I am doing some research on using Playwright with the testing service and was not able to find answers to a couple questions. 

Using dotnet, C#, & xUnit, connecting using a bearer token to the Azure endpoint. How can I specify for the service to use Edge or Chrome instead of just Chromium? I don't see settings in the `BrowserTypeConnectOptions` or `BrowserNewContextOptions`. Is there a way to specify it as a query string on the URL?

Any runs report as `Reporting Disabled`. Is it possible to enable this when running locally or is it something which will only work in a pipeline by uploading a TRX output?

**Comment by puagarwa** [comment]
Hi @JDCain, Great to hear your interest in using dotnet. 

Regarding chrome/mdesge
You can use it via option channel https://playwright.dev/dotnet/docs/browsers#google-chrome--microsoft-edge

We have recently added first class support for Nunit runner in playwright testing service and here is example https://playwright.dev/dotnet/docs/browsers#google-chrome--microsoft-edge, this enabled reporting as well without any need of CI or trx output. 
We dont yet natively support Xunit but I am interested in understanding your research and then see how can we help it.  I can arrange a sync up call to over it. please drop a email at [playwrighttesting@microsoft.com](mailto:playwrighttesting@microsoft.com)

**Comment by JDCain** [comment]
When locally using `LaunchAsync` it's clear how to pass the channel, however when using `ConnectAsync` to access `wss://eastus.api.playwright.microsoft.com` the class `BrowserTypeConnectOptions` which is taken by `ConnectAsync` does not include a channel property. 

Unfortunately using NUnit is not an option as we currently have thousands of xUnit based dotnet Selenium tests with custom xUnit behaviors. I am looking at using this `IWebDriver` abstraction (https://github.com/thomhurst/Selenium.PlaywrightDriver) to switch out existing tests to xUnit.

**Comment by puagarwa** [comment]
Hi @JDCain ,
    You can pass channel browser info via header x-playwright-launch-options with value BrowserTypeLaunchOptions

                    Headers = new List<KeyValuePair<string, string>>
                    {
                        new KeyValuePair<string, string>("Authorization", $"Bearer {token}"),
                        new KeyValuePair<string, string>("x-playwright-launch-options", System.Text.Json.JsonSerializer.Serialize(new BrowserTypeLaunchOptions(){Channel= "msedge"}, new JsonSerializerOptions() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull }))
                    },

**Comment by JDCain** [comment]
@puagarwa What about passing the bearer token via the ` --logger "microsoft-playwright-testing"`? 
I've set it via `$env:PLAYWRIGHT_SERVICE_ACCESS_TOKEN` and the url `$env:PLAYWRIGHT_SERVICE_URL=wss://eastus.api.playwright.microsoft.com/accounts/<secret>/browsers` but I still get the error: `1) The authentication token provided is invalid. Please check the token and try again.` Are there any other settings I am missing?

**Comment by puagarwa** [comment]
HI @JDCain , I will try it tomorrow, but it could be due to default value of param ServiceAuthType as "EntraId" whereas in your case it should be "AccessToken" since you are using token auth. Would you mind either 

defining runsettings and add 
    <TestRunParameters>
        <Parameter name="ServiceAuthType" value="AccessToken" />
    </TestRunParameters>

or pass it from dotnt cli as 
--% -- TestRunParameters.Parameter(name=\"ServiceAuthType\", value=\"AccessToken\")

**Comment by JDCain** [comment]
Setting `ServiceAuthType` did make it so I no longer get errors. I also made sure the `RunId` would match between the logger and the test run. However, no logging ever shows up in the UI. In fact they all list as `Reporting Disabled`
![Image](https://github.com/user-attachments/assets/6490d379-3e95-4cd0-855d-cd330997268c)

**Comment by puagarwa** [comment]
Hi @JDCain , As i mentioned earlier we havent tested our logger for Xunit yet so its possible it may not work. I can take a look at it tomorrow if you can share small repro (possibly repo)

Meanwhile, can you share your subscription Id so that i can take a look at telemetry.

**Comment by JDCain** [comment]
The reporting is a [ITestLoggerWithParameters](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/playwrighttesting/Azure.Developer.MicrosoftPlaywrightTesting.TestLogger/src/PlaywrightReporter.cs) so it should be agnostic to whatever testing framework is being used. I'll send you the id directly.

**Comment by puagarwa** [comment]
Hi @JDCain , I spent some time with Xunit + service. Good part is both cloud browser and reporting works. here are my findings and suggestion
- Make sure you use different runId every time --> in your example in discord (BaseClass) you have hard coded it. I will suggest pass it via env variable like this $"wss://eastus.api.playwright.microsoft.com/accounts/secret/browsers?os=linux&runId={Environment.GetEnvironmentVariable("PLAYWRIGHT_SERVICE_RUN_ID")}
- You can remove runId from runsettings as well, logger consider this env variable PLAYWRIGHT_SERVICE_RUN_ID, as long as you set this, it should work fine
- For AccessToken, please pass it from env variable PLAYWRIGHT_SERVICE_ACCESS_TOKEN, logger takes it from this env variable.

Please try these and let me know. I will also test to add working example in this repo in few days.

**Comment by JDCain** [comment]
There appear to be several settings which cannot be set via environmental variables with the reporter and still need the run settings. For example I can't use the key unless I set `ServiceAuthType` in the run settings: https://github.com/Azure/azure-sdk-for-net/blob/c7aebd5804617eed4744bf97dec8636a9ab347ef/sdk/playwrighttesting/Azure.Developer.MicrosoftPlaywrightTesting.TestLogger/src/PlaywrightReporter.cs#L96C9-L96C1

Is there any trick to getting video and screenshots to upload? I have them working locally but when using the service they never appear.

**Comment by puagarwa** [comment]
HI @JDCain , in my above message. you could still use runsettings. I only asked to pass Token and runId from env variable instead of runsettings. Rest everything can either be passed either via runsettings or via cli params (--% -- TestRunParameters.Parameter(name="ServiceAuthType", value="AccessToken")). 

Yeah, similar to how i have done it for Nunit in my [example](https://github.com/microsoft/playwright-testing-service/blob/main/samples/.NET/NUnit/PageTestWithArtifact.cs) in this repo, we could do it for Xunit as well. basically the trick is to enable those by following playwright docs and then make sure add it in testcontext. I havent tried this yet but should be doable.

**Comment by JDCain** [comment]
TestContext does not exist in xUnit currently so that can't be used to attach things via the logger. 

Also how would that work since the test is running remotely in the service? When I run a test with video on the cloud service no video is locally created which I could attach.

**Comment by puagarwa** [comment]
HI @JDCain ,
   Yes, As you mentioned testContext doesnt exist in Xunit and its open ask by many on thier [repo ](https://github.com/xunit/xunit/issues/621) from many years.

I spend time on trace/video in Xunit and here is my findings
- You could generate trace and video locally even when using cloud browser, the way cloud browser works it always fetches the artifacts at client side.
- Even though we can generate these artifacts, due to Xunit lack of support for TestContext and AddTestAttachment its not possible to attach it to reporting. (Xunit [issue](https://github.com/xunit/xunit/issues/936))

Here is modified code to enable trace and video. With this you should see trace and videos collected in bin\Debug\netX.0 location 

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json.Serialization;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Playwright;
using Azure;
using System.Reflection.PortableExecutable;

namespace PlaywrightTestsXUnit
{
    public class PlaywrightTestWithArtifact : IAsyncLifetime, IDisposable
    {
        private IPlaywright _playwright;
        private IBrowser _browser;

        public async Task InitializeAsync()
        {
            _playwright = await Playwright.CreateAsync();
            // use endpoint, runid from environment variables
            _browser = await _playwright.Chromium.ConnectAsync($"{Environment.GetEnvironmentVariable("PLAYWRIGHT_SERVICE_URL")}?os=windows&runId={Environment.GetEnvironmentVariable("PLAYWRIGHT_SERVICE_RUN_ID")}", new BrowserTypeConnectOptions
            {
                ExposeNetwork = null,
                Headers = [new KeyValuePair<string, string>("Authorization", $"Bearer {Environment.GetEnvironmentVariable("PLAYWRIGHT_SERVICE_ACCESS_TOKEN")}"), // use token from env variable
                new KeyValuePair<string, string>("x-playwright-launch-options", System.Text.Json.JsonSerializer.Serialize(new BrowserTypeLaunchOptions { Channel= "msedge", Headless = false}, new JsonSerializerOptions() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull }))],

                SlowMo = null,
                Timeout = null
            });
            Context = await _browser.NewContextAsync(ContextOptions());

            // Enable Trace
            await Context.Tracing.StartAsync(new()
            {
                Title = $"{Guid.NewGuid}",
                Screenshots = true,
                Snapshots = true,
                Sources = true
            });
            Page = await Context.NewPageAsync();
            //await Context.Tracing.StartAsync(new TracingStartOptions()); // not needed
        }
        public async Task DisposeAsync()
        {
            var tracePath = $"trace-{Guid.NewGuid()}.zip"; // Since Xunit doesnt support TestContext hence using guid, there are workaround using reflection to get testName if needed for trace file name 
            await Context.Tracing.StopAsync(new()
            {
                Path = tracePath
            });
            var videoPath = $"trace-{Guid.NewGuid()}.webm"; // Since Xunit doesnt support TestContext hence using guid, there are workaround using reflection to get testName if needed for video file name
            await Context.CloseAsync();
            if (Page.Video != null)
            {
                await Page.Video.SaveAsAsync(videoPath); // this is required to get video locally when using cloud browser
                //TestContext.AddTestAttachment(videoPath, description: "Video"); // cant work in Xunit
            }
            return;// Task.CompletedTask;
        }

        public IBrowserContext Context { get; set; }
        public IPage Page { get; set; }
        public virtual BrowserNewContextOptions ContextOptions()
        {
             
            return new()
            {
                Locale = "en-US",
                ColorScheme = ColorScheme.Light,
                RecordVideoDir = ".videos" // required to enable video
            };
        }
        public void Dispose()
        {
            _playwright.Dispose();
        }
    }
}

```

**Comment by JDCain** [comment]
Is there documentation for the API used to upload the artifacts, and does that API allow you to upload artifacts after the results have already been uploaded?  e.g. Could I create a separate job which uploads the artifacts after the run completes without using the logger? I do something similar to this with our current custom `ITestLogger` and videos with Selenium.

Also does the API instead allow for say appending links or notes to a run? There was some concern about uploading the videos at all as there could be information we don't want to upload to the cloud in the videos. For example in TFS you can append notes to a run via a markdown file with links.

**Comment by puagarwa** [comment]
> Is there documentation for the API used to upload the artifacts, and does that API allow you to upload artifacts after the results have already been uploaded? e.g. Could I create a separate job which uploads the artifacts after the run completes without using the logger? I do something similar to this with our current custom `ITestLogger` and videos with Selenium.

We have API but it wont allow you to upload artifacts post run completion (which happen from service logger). I understand your ask and intent here but its not possible yet. please open a feature ask in github issues. 

> Also does the API instead allow for say appending links or notes to a run?

Currently no, we dont allow any update in run/result post run completion. 

> This video recording also does not work for me when using the cloud service
Yes, i can also see the issue, I will take a look at it and check whats the issue. It works in Nunit/MSTest so need to check once.

**Comment by puagarwa** [comment]
Hi @JDCain , I found the issue with empty view. It was due to Test is creating local Page, hence it is not using global Page which we created in initialize. 
In class UnitTest1, Comment this line 
`Page = await Context.NewPageAsync();`

Also, In my above fixture, i put OS name as windows, you could change it to linux if needed
`_browser = await _playwright.Chromium.ConnectAsync($"{Environment.GetEnvironmentVariable("PLAYWRIGHT_SERVICE_URL")}?os=windows&runId={Environment.GetEnvironmentVariable("PLAYWRIGHT_SERVICE_RUN_ID")}`
We could make code changes to honor runsettings value if needed.
