### ISSUE TITLE
[BUG]:Playwright-testing-Automation:Not able to click UI radio buttons in latest angular version webpages.

### ISSUE THREAD

**Issue by AshikSajjad** [microsoft/playwright-testing-service#153]
**Describe the bug**

I tried to automate my front end application. I tried it with record option. When I tried to click on the radio buttons the page start moving up and down. After so many analysis I found that older angular version didn't have this issue. My web page is using latest angular version and this is applicable for all the radio buttons. Is there any solutions for this??

**Comment by puagarwa** [comment]
@AshikSajjad Your issue seems to be for https://github.com/microsoft/playwright , I suggest filing this issue upstream.
