### ISSUE TITLE
Microsoft Playwright Testing needs different configuration to run older Playwright versions

### ISSUE THREAD

**Issue by vvs11** [microsoft/playwright-testing-service#17]
The service config mentioned [here](https://github.com/microsoft/playwright-testing-service/blob/main/samples/get-started/playwright.service.config.ts) is supported for Playwright 1.37 and above. This cannot be used to run tests using older versions of Playwright.

**Comment by puagarwa** [comment]
closing the issue as 1.36 is more than year old and we dont see any requirement.
