### ISSUE TITLE
Allow using Proxy 

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright-testing-service#51]
**Is your feature request related to a problem? Please describe.**
Tests fail when using proxy in the launchOptions in the main playwright.config.js

**Describe the solution you'd like**
Allow using proxy when running tests against the service

Hi there. Is there anyway you can support the proxy configuration when running tests against the service?

At the moment, I am using this to test on different locations

```
launchOptions: {
          proxy: {
            server: `myproxy.com:11000`,
            username: 'Myuser',
            password:  'Password',
          },
        },
```
It works fine when running the tests on Selenium Grid or locally, however it fails the tests on the service. 

Thanks!

AB#1894966

**Comment by imartinflores** [comment]
Hi there guys, just wondering if you could reproduce this?

**Comment by puagarwa** [comment]
HI @imartinflores , proxy would work only if exposeNetwork is undefined. can you once try commenting this line https://github.com/microsoft/playwright-testing-service/blob/main/samples/get-started/playwright.service.config.ts#L56 or set it to undefined and report how it goes. Just to be clear, by doing this please make sure your proxy is accessible from public network so that service browsers can access it.

**Comment by imartinflores** [comment]
hey @puagarwa ! So, I ve been trying to double check what the issue is. I could see that using proxy in the config file (as it should be) works fine. However, we have a couple of tests where we override the proxy server with 

```
test.use({
    proxy: {
         server: newserver.myproxy.com
    }
})
```

I think this is the scenario where the test fails. In the grid we run the tests right now or even locally, it works good, it overrides the proxy server and still takes the username and password from the config file, but I think this is where it fails when using the service, seems like it does not take into account the credentials used in the config file. We can change the configuration a bit to allow us to not need to override the server name, but just in case you want to have a look.
Any other help you need, please do let me know.

Thanks!

**Comment by puagarwa** [comment]
HI @imartinflores Really appreciate you going deep into the issue and able to pin point the scenario which works and which doesnt with service. It is really helpful. 

Just to summarize, your test with proxy works in service mode if you use proxy from config file but faces issue when you try to override proxy config from outside of config.

About the issue, i noticed you are only passing server info without credentials which basically means your proxy wont use credential, hence wont work. Can you try to also set userName/password in test.use like below and try it. 
test.use({
  proxy: {
       server: `server`,
       username: 'user',
       password: 'your-password'
  }
})
I understand why it is working in local mode without credential, whats most likely happening is your local machine IPs are permitted on proxy without any credential, you can confirm this by removing credentials from config in local mode and it would work fine.  But service browsers IPs would only be permitted to use proxy with credentials hence you need to make sure you pass credentials when using with service.

Playwright override proxy configs completely if you set it inside test.use and ignore whats being passed in config file. hence if you only set server and no credential, it would treat it as null.

**Comment by imartinflores** [comment]
Hi @puagarwa , thanks for the prompt response. Yes, I have tried that and specifying credentials in there (test.use()) works as well. Oh I see, so it's probably the case also with the machines hosting our grids? Their IPs may also be permitted on proxy without credentials? That makes sense.

Thanks a lot again, happy to help when I can. If I find something else or a different scenario, I will file a new issue here. I think we can close this one if you agree!
