### ISSUE TITLE
Ability to add Tags for "creating the new workspace" for playwright azure service

### ISSUE THREAD

**Issue by PavanMudigondaTR** [microsoft/playwright-testing-service#53]
**Is your feature request related to a problem? Please describe.**
At my org, we need to add few tags to be able to create RG or any resources in general. Current layout of the "Create new workspace" is not allowing me to add tag so i am not able to get started with this service.

**Describe the solution you'd like**
Please add ability to add tags 
**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/microsoft/playwright-testing-service/assets/86745613/7cc41201-30cd-44ed-b1e8-fb8be8496864)

AB#1896437

**Comment by PavanMudigondaTR** [comment]
please close this. John Stallo has given alternate solution to create resource group.

**Comment by johnsta** [comment]
For other folks with the same question:
You can manage the workspaces you’ve set up just like any other Azure resource within the [Azure Portal](https://portal.azure.com/). In the Azure Portal, just enter the workspace name in the search bar, and from there you can get to the resource to add tags, set access, etc. as you normally would for another other Azure resource.
 
Depending on your scenario needs, you can actually create a workspace resource directly in the Azure Portal. You can do this by navigating to portal.azure.com, go to "Create a resource", and search for "Microsoft Playwright Testing" to start the process. Any workspace resource you create there will automatically appear in the [Playwright portal](https://playwright.microsoft.com).
