### ISSUE TITLE
[BUG] 503 Service Unavailable error for West Europe region.

### ISSUE THREAD

**Issue by vikasmourya89** [microsoft/playwright-testing-service#55]
**Describe the bug**
503 Service Unavailable error for West Europe region.

**Error**
WebSocket error: wss://westeurope.browser.playwright.microsoft.com/ws 503 Service Unavailable
The service is currently unavailable. Engineers have been notified and are working on resolving the issue. Please try again after some time.
The region and service id for this test run are : westeurope, 6fce7c6c-cbfb-49b2-b215-1b0a7d8ed3a5

=========================== logs ===========================
<ws connecting> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession
<ws error> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established
<ws connect error> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established
<ws disconnected> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=
<ws connecting> wss://westeurope.browser.playwright.microsoft.com/ws
<ws unexpected response> wss://westeurope.browser.playwright.microsoft.com/ws 503 Service Unavailable
The service is currently unavailable. Engineers have been notified and are working on resolving the issue. Please try again after some time.
The region and service id for this test run are : westeurope, 6fce7c6c-cbfb-49b2-b215-1b0a7d8ed3a5

**Comment by puagarwa** [comment]
HI @vikasmourya89 , We looked into our telemetry and it is due to wrong caps being passed in your request. Ideally it should have been 400 but due to error handling issue, it returned 503.

Can you please check [caps](https://github.com/microsoft/playwright-testing-service/blob/main/samples/get-started/playwright.service.config.ts#L46) and try again. If possible you could share your service config to confirm with us.

**Comment by vikasmourya89** [comment]
Yes, you are correct. Json.Stringify was incorrect in caps. 
It is working now. 
Thanks!
