### ISSUE TITLE
TypeError: (0 , _test.defineConfig) is not a function

### ISSUE THREAD

**Issue by maharrshi** [microsoft/playwright-testing-service#56]
I used the playwright.service.config.ts file as mentioned in the article and my playwright version is 1.38.1. 
The line import dotenv from 'dotenv'; was throwing errors so i used below line as alternative:
 import { config } from 'dotenv';
config();
I also created a .env file named as playwrightTestingService.env and put the two variables in it (PLAYWRIGHT_SERVICE_ACCESS_TOKEN and PLAYWRIGHT_SERVICE_URL).
when i run the command npx playwright test --config=playwright.service.config.ts --workers=20 , I am getting TypeError: (0 , _test.defineConfig) is not a function

AB#1898417

**Comment by Sid200026** [comment]
Hi @maharrshi, 

I wasn't able to reproduce this issue when using playwright version 1.38.1. Could you help with the following details
- Modified `playwright.service.config.ts` file being used
- Operating System
- Node version 

Regarding the dotenv issue, could you provide the error that was being thrown earlier?

Lastly, by default dotenv npm library searches for the file `.env` only. If you need to use another name for the env file, you'd need to set the path explicitly. ( Reference - https://github.com/motdotla/dotenv#path )

```js
config({ path: 'playwrightTestingService.env' });
```

**Comment by Sid200026** [comment]
Hi @maharrshi, let me know if you had the chance to capture the above information for us to reproduce the issue.

**Comment by Sid200026** [comment]
Closing this issue for now, feel free to reopen if the issue persists.
