### ISSUE TITLE
[BUG]: Page setup exceeds 10 seconds while executing component test cases in playwright service

### ISSUE THREAD

**Issue by AnandhkumarM** [microsoft/playwright-testing-service#59]
**Describe the bug**
When we execute the tests in playwright services the `page` setup exceeds 10 seconds, so the test cases are failing due to test timeout of 10 seconds, whereas in local execution its not taking that long.

**To Reproduce**
1. Trigger the component tests in playwright service
2. See error in report

**Expected behavior**
The `page` setup should not take 10 seconds

**Screenshots**

Playwright service execution:-
<img width="211" alt="anysnap-12-oct-2023-at-4-37-59-pm" src="https://github.com/microsoft/playwright-testing-service/assets/122448359/d0ef8ce6-9b7e-42c4-a6c3-1ce9a3b08241">

![AnySnap 12 Oct 2023 at 8_29_59 PM](https://github.com/microsoft/playwright-testing-service/assets/122448359/49498c57-39c0-45d5-9c9d-a016a8a85408)

Local execution:-
<img width="232" alt="anysnap-12-oct-2023-at-4-30-34-pm" src="https://github.com/microsoft/playwright-testing-service/assets/122448359/c7ce3a48-98e1-4406-a474-a2b658c676d0">

**Setup information (please complete the following information):**
 - Azure Subscription Id: 316e975c-b0ca-41f9-a19a-328d358ad778
 - Workspace Name: Component
 - Service trace Id (if available):
 - Log snippet (if available):
 - Browser on which tests are executed (if applicable): Chromium, Firefox, Webkit
 - Time range (in PST) when the issue was experienced: 12-10-2023 4:00 AM
 - Playwright Version: 1.35.1
- Client machine OS: Mac OS Ventura 13.4.1 (22F82)
- OS requested on Service: Linux

AB#1900502

**Comment by puagarwa** [comment]
Hello @AnandhkumarM thanks for reporting the issue. I need few details 
- Location of your client machine
- Location of your Web endpoint 
- Is your webapp public ?
- Nature of your web endpoint, is it resource heavy webapp ?
- is this issue happning every time or sometime ?

As seen from your trace, opening webapp page taking 5sec from our browser infra, hence we need to understand the reason. You could try out some other generic webapp page and it wont take that long time.

I also checked our telemetry and found one things
- I observe you are trying to use lots (sometime more than 300) of parallel request but just to mention your parallel browser quota is 50 hence all other request would wait in queue or returned with 429, hence better to use worker less than 50

**Comment by AnandhkumarM** [comment]
> Hello @AnandhkumarM thanks for reporting the issue. I need few details
> 
> * Location of your client machine
> * Location of your Web endpoint
> * Is your webapp public ?
> * Nature of your web endpoint, is it resource heavy webapp ?
> * is this issue happning every time or sometime ?
> 
> As seen from your trace, opening webapp page taking 5sec from our browser infra, hence we need to understand the reason. You could try out some other generic webapp page and it wont take that long time.
> 
> I also checked our telemetry and found one things
> 
> * I observe you are trying to use lots (sometime more than 300) of parallel request but just to mention your parallel browser quota is 50 hence all other request would wait in queue or returned with 429, hence better to use worker less than 50

Hi @puagarwa ! 

Sorry, missed to specify that the playwright version I mentioned in the setup information is an experimental playwright version : `experimental-ct-react": "^1.35.1"` that we use to execute **playwright component tests.** 

-Location of your client machine : Chennai, Tamil Nadu, India

-Location of your Web endpoint :  
-Is your webapp public ?
-Nature of your web endpoint, is it resource heavy webapp ?

To answer the three questions above, in playwright component tests we just mount the component in DOM, so it doesn't involve web apps and endpoint.

-Is this issue happening every time or sometime ? It happens every time 

I tried executing with 40 workers and still the issue persists.

Additionally, we made a special request to allocate 100 workers for our subscription ID.

**Comment by AnandhkumarM** [comment]
HI @puagarwa 

I executed using headless: true and it doesn't seem to make any difference in the results.

Answering to other questions:

Does this issue happen every time, if not then how frequently we hit the issue : 
-It happens every time when we execute in playwright service

Does it happen more on particular browser ? 
-It happens mostly on `Webkit` and `Firefox`

Can you try in local mode with more workers and see if it happen in local as well ? 
-I tried increasing the local workers to 8 and executed the tests they were stable and I didn't face the issue.

you could upgrade to 1.38 and see if it make any change. 
-I updated the playwright version to `experimental-ct-react": "^1.38.1"` and executed and the issue still seems to persist.

**Comment by puagarwa** [comment]
HI @AnandhkumarM thanks for sharing details
I would need your help me to provide repro if you can so that i can debug the issue. 

One question though on your above response, You said issue happen mostly on webkit and firefox, does it mean it doesnt happen on chromium or happen less often on chromium ? Did you tried increasing 10s timeout and see if that solves the issue ?

**Comment by puagarwa** [comment]
HI @AnandhkumarM , Did you get chance to look into it, If needed we can setup sometime to go over it on a call.

**Comment by AnandhkumarM** [comment]
Hi @puagarwa , Since its a private repo, it won't be possible to share . Maybe we can setup a call sometime .

**Comment by puagarwa** [comment]
As discussed over call, due to networking we need to have higher timeout. Let me know if any help needed.
