### ISSUE TITLE
[BUG]:TestRunID not picking up the value

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright-testing-service#63]
**Describe the bug**
Hi there, not sure if someone else experienced this, but I am hardcoding a string value as the runId and nothing comes through the dashboard. It's still showing TestRun#build. Am I missing something or doing something wrong ?

**To Reproduce**
1. Step 1: Replace the .env variablle on the runId value wrapped in the conectOptions with some string.
2. Step 2: Run the tests

**Expected behavior**
TestRun should have the name assigned in the config file when lookin at the dashboard

```
 connectOptions: {
      wsEndpoint: `${process.env.PLAYWRIGHT_SERVICE_URL}?cap=${JSON.stringify({
        // Can be 'linux' or 'windows'.
        os,
        runId: `TestingExample - ${new Date().toISOString()}`
      })}`,
      timeout: 30000,
      headers: {
        'x-mpt-access-key': process.env.PLAYWRIGHT_SERVICE_ACCESS_TOKEN!
      },
      // Allow service to access the localhost.
      exposeNetwork: '<loopback>'
    }
```
Dashboard test run name:
TestRun#build

AB#1907781

**Comment by puagarwa** [comment]
Hi @imartinflores I just tried the above fixture change and i can see changed runId showing up in activityLog
![image](https://github.com/microsoft/playwright-testing-service/assets/28705989/5dbf06bd-33a2-4f77-92e4-48bc2fa3c551)

I want to point one diferent issue in above snippet that if you put runId value directly then every individual session will show up as different entry in activityLog dashboard, which may not be inteneded as you like to see summary of entire run. hence, here is what i would suggest
change line https://github.com/microsoft/playwright-testing-service/blob/main/samples/get-started/playwright.service.config.ts#L25 to

```
// Name the test run if it's not named yet.
process.env.PLAYWRIGHT_SERVICE_RUN_ID = process.env.PLAYWRIGHT_SERVICE_RUN_ID || `TestingExample - ${new Date().toISOString()}`
```
and no other change in fixture.

**Comment by imartinflores** [comment]
hey @puagarwa that is what we've done initially but it is not being updated in the activityLog. We hardcoded the value directly in the runId to see if that makes a change but nothing either..
Is there any other place where I should look into ? should I enable logs ?
Thanks

**Comment by puagarwa** [comment]
> lace where I should look into ? should I enable logs

Logs wont help much here unless you add your own logs to print the value. 
check these things
- runId is set to runId: process.env.PLAYWRIGHT_SERVICE_RUN_ID in connectOptions
- set this before connectOptions process.env.PLAYWRIGHT_SERVICE_RUN_ID = process.env.PLAYWRIGHT_SERVICE_RUN_ID || `TestingExample - ${new Date().toISOString()}`
- make sure you are using right config file, probably print some console log in config file.

**Comment by imartinflores** [comment]
@puagarwa  I have added a console.log, I can see this being printed:

"Landers_Build - 2023-10-25T13:25:23.721Z

However in the activityLog, it seems the value is being truncated:

TestRun#3.721Z (Matches with the last part of the build name we used)

**Comment by puagarwa** [comment]
To rule out truncate issue, you can actually put some random string because timestamp could be same for other reasons as well.

You could enable DEBUG=pw:channel:command* logs, and search for log like this
`pw:channel:command     wsEndpoint: 'wss://eastasia.api.playwright-int.io/api/authorize/connectSession?cap={"os":"windows","runId":"TestingExample - 2023-10-25T13:46:03.845Z"}',`

this will confirm value being sent from client side. 
PS: Dont enable this log in CI since this print accessKey as well.

**Comment by puagarwa** [comment]
HI @imartinflores We dont have any such truncate logic, i have tested different values and all are working properly.

It seems like you are always seeing the same value "TestRun#Build" , can you change your value to "AnyRandomString" and see what do you see.

Another way would be you try our sample suite with different value of runId as i mentioned earlier to validate it.

**Comment by imartinflores** [comment]
@puagarwa we can close it - I've tried it again on my own and I can see the name coming in full now. On my colleague machine, we still see it truncated, so we will dig into. Thanks for the help!

**Comment by puagarwa** [comment]
Glad to hear, it resolved for you. Feel free to open it if you have again or another issue.

**Comment by puagarwa** [comment]
@imartinflores Actually, we do have a bug which truncate anything after _ from runId string, We will fix it asap.

**Comment by imartinflores** [comment]
Ahh alright, cool, makes sense. Thanks for the update!

**Comment by puagarwa** [comment]
@imartinflores This is fixed now.
