### ISSUE TITLE
[BUG]: Broken link in Getting Started Sample

### ISSUE THREAD

**Issue by shon-shah** [microsoft/playwright-testing-service#65]
"quickstart" link* on the second line of **Get Started Sample** section at https://github.com/microsoft/playwright-testing-service/tree/main/samples/get-started#get-started-sample is broken.

(* pointing to https://github.com/microsoft/playwright-testing-service/blob/main/docs/quickstart.md) 

AB#1908631

**Comment by vvs11** [comment]
Updated the link. Thanks for pointing out.
