### ISSUE TITLE
I want to know the host specifications.

### ISSUE THREAD

**Issue by gatsukichi** [microsoft/playwright-testing-service#67]
My tests use some memory and cpu/gpu resources of the host where the browser is displayed.

Therefore, it is necessary to know the specifications of the host on which the test actually runs.

I couldn't find it anywhere in azure playwright testing.

What are the specifications?

AB#1910145

**Comment by vvs11** [comment]
Hi @gatsukichi , Thanks for writing to us. 

Currently, each browser is hosted on a container instance that has 2 cores of CPU and 5 GB of memory. These specifications might be adjusted in the future based on requirements. 

Feel free to reach out if you have more questions.
