### ISSUE TITLE
Unable to run playwright test cases in Microsoft edge in Incognito/private mode after Plywright Service Integration

### ISSUE THREAD

**Issue by Dinesh2703** [microsoft/playwright-testing-service#74]
In my local machine i set up palywright service and ran test case with persistent browser and test url without authentication.
But in Azure pipeline i cannot run test cases with persistent browser so i had to modify code and ran my test cases in incognito/private mode using edge browser. But its not able to open the test url for which i wrote test cases. Its giving timeout error. 
The url is http and not https. I am trying to run in my local as well as in azure pipeline. Its giving same error i.e. timeout for test url.

Below is the screenshot of the error.
<img width="742" alt="MicrosoftTeams-image (4)" src="https://github.com/microsoft/playwright-testing-service/assets/41935464/6125d3f3-8f06-47ce-9c4d-90f2a0e8ebce">
<img width="742" alt="MicrosoftTeams-image (4)" src="https://github.com/microsoft/playwright-testing-service/assets/41935464/80d3aa04-d7b9-4909-872b-044d9385007a">

AB#1919606

**Comment by puagarwa** [comment]
HI @Dinesh2703 I am able to repro the issue. It seems like our browser infra is not able to load this DNS/IP. While I am working on fix for it. I have short term workaround to unblock you.

You can make this change in playwright.service.config.ts file, set exposeNetwork param to '*' from current value of <loopback>
exposeNetwork: '*'

**Comment by Dinesh2703** [comment]
> HI @Dinesh2703 I am able to repro the issue. It seems like our browser infra is not able to load this DNS/IP. While I am working on fix for it. I have short term workaround to unblock you.
> 
> You can make this change in playwright.service.config.ts file, set exposeNetwork param to '_' from current value of exposeNetwork: '_'

Hi,
It did not work, but today i am getting another error:

![image](https://github.com/microsoft/playwright-testing-service/assets/41935464/8454754d-fd8b-4a52-9b6d-5e8112106810)

**Comment by Dinesh2703** [comment]
> HI @Dinesh2703 I am able to repro the issue. It seems like our browser infra is not able to load this DNS/IP. While I am working on fix for it. I have short term workaround to unblock you.
> 
> You can make this change in playwright.service.config.ts file, set exposeNetwork param to '_' from current value of exposeNetwork: '_'

Hi @puagarwa 
exposeNetwork:'_' did not work... but setting it to '*' worked. 
there is one more issue.. after setting headless = false, its working but browser is not opening.

**Comment by puagarwa** [comment]
> > HI @Dinesh2703 I am able to repro the issue. It seems like our browser infra is not able to load this DNS/IP. While I am working on fix for it. I have short term workaround to unblock you.
> > You can make this change in playwright.service.config.ts file, set exposeNetwork param to '_' from current value of exposeNetwork: '_'
> 
> Hi @puagarwa exposeNetwork:'_' did not work... but setting it to '*' worked. there is one more issue.. after setting headless = false, its working but browser is not opening. Its still working on headless mode

Sorry, i missed putting '*' thats correct. I looked into it further and actually the reason its not working from browser without exposeNetwork is because your endpoint is not opened to all public but it has network restriction. So either you stay with with exposeNetwork solution or we could provide you our IP range which you can whitelist if possible.

Coming back to headfull mode, thats expected that you wont see browser being opened in your machine since its remote browser. Hence using headful mode is not that meaningful if idea is to look at execution but rather trace and logs are more useful.

**Comment by Dinesh2703** [comment]
> > > HI @Dinesh2703 I am able to repro the issue. It seems like our browser infra is not able to load this DNS/IP. While I am working on fix for it. I have short term workaround to unblock you.
> > > You can make this change in playwright.service.config.ts file, set exposeNetwork param to '_' from current value of exposeNetwork: '_'
> > 
> > 
> > Hi @puagarwa exposeNetwork:'_' did not work... but setting it to '*' worked. there is one more issue.. after setting headless = false, its working but browser is not opening. Its still working on headless mode
> 
> Sorry, i missed putting '*' thats correct. I looked into it further and actually the reason its not working from browser without exposeNetwork is because your endpoint is not opened to all public but it has network restriction. So either you stay with with exposeNetwork solution or we could provide you our IP range which you can whitelist if possible.
> 
> Coming back to headfull mode, thats expected that you wont see browser being opened in your machine since its remote browser. Hence using headful mode is not that meaningful if idea is to look at execution but rather trace and logs are more useful.

ok @puagarwa if putting '*' is fine according to you then i will keep it like that. and i dont hv any problem with headless mode. i just wondered so i asked to confirm. Thanks @puagarwa

**Comment by puagarwa** [comment]
@Dinesh2703 Regarding exposeNetwork , its fine to use from feature standpoint when you have private endpoint not exposed publicly however, it does have some perf impact on test latency so we can evaluate and if we found its impacting your test latency then we can explore whitelisting service IP range. BTW, i am wondering you would have already whitelisted ADO IP range as this is accessible from ADO agents.

**Comment by puagarwa** [comment]
Closing this for now, let me know if you have more queries.
