### ISSUE TITLE
Increase workers to 250

### ISSUE THREAD

**Issue by MoAlrubaie** [microsoft/playwright-testing-service#77]
## Quota Increase Request

**Quota to Increase:**
 

[Specify which quota you would like to increase]

* [x] Maximum number of workers for the workspace
* [ ] Maximum number of workspaces per subscription
* [ ] Throttling limits
* [ ] Other

 

**Business Justification:**

We have huge number of tests which we need to run in more resources isolation for stability. Also, we are running some load tests which we need higher number of workers.

**Requested New Quota Limit:**

250 per workspace

**Additional Information:**

We will appreciate it if we can get this soon. At Brightdrop, we work on very intense deadlines.

**Setup Information:**

- **Subscription ID:** 2e4630f8-4506-4e13-97f9-e47344655c69
- **Workspace ID:** eastus_d0a0d9e8-9420-4c77-8957-e5691e17f971

**Disclaimer:**

Please note that while we will do our best to accommodate your quota extension request, we may not be able to fulfill every request due to resource constraints. We will review your request and provide a response as soon as possible.

AB#1919892

**Comment by vvs11** [comment]
Hi @MoAlrubaie , 
Thanks for writing to us. Could you help us understand what kind of tests you are running that would require isolation. Also, how are you planning to run load tests? 
Thanks

**Comment by MoAlrubaie** [comment]
Hi @vvs11 ,
We are running some extensive tests which we includes some Backend calling activities as well as some network interceptions. Working with 50 workers has shown great improvements. This is why we are looking for more.
For load testing, we are doing a loop around the test with determining the number of workers. We are planning to have each worker act as a user (in theory).

**Comment by puagarwa** [comment]
Hi @MoAlrubaie Would you be able to us below info
- Playwright version you intend to use
- OS requested for browsers from test linux or windows

**Comment by MoAlrubaie** [comment]
Hi @puagarwa ,
* We are currently using 1.40.0
* Linux is our intended OS for now, later we might expand to windows
* For load testing, the individual test duration will be between 2-3 minutes. For other E2E tests, they will be around 20 seconds - 80 seconds

**Comment by puagarwa** [comment]
HI @MoAlrubaie Your quota is increased to 250, please feel free to use it and let us know if any issue.

**Comment by puagarwa** [comment]
HI @MoAlrubaie did you get a chance to try it out. I am closing the issue but feel free to open issue if you face any issue.

**Comment by vvs11** [comment]
Hi @MoAlrubaie 
We'd like to understand your scenario better and get feedback about the service. Would you be open to a small conversation?
You can reach out to us at playwrighttesting@microsoft.com or let us know how we can reach out to you to take it forward. 
Thanks

**Comment by MoAlrubaie** [comment]
Hi @vvs11 ,
Sorry I was out in vacation. Thanks, I will send an email out today, would like to discuss as we have several scenarios. and we are planning to expand the use of the service as well.

Thanks,
Mo
