### ISSUE TITLE
Support for `args`, e.g. --use-fake-device-for-media-stream

### ISSUE THREAD

**Issue by martinklepsch** [microsoft/playwright-testing-service#78]
**Is your feature request related to a problem? Please describe.**
We're testing an app involving camera and mic access, without the ability to access those browser features our tests will not be able to run using the Playwright Testing Service. 

**Describe the solution you'd like**
Ability to provide `args` for browsers. For example I would like to launch Chromium with flags to enable camera and mic access. 

AB#1919898

**Comment by puagarwa** [comment]
HI @martinklepsch Did you try passing args from launchOptions in config ? Even though browser.connect API doesnt have option to pass it but i think launchOption would work for you. please give it a try and confirm.

https://playwright.dev/docs/api/class-testoptions#test-options-launch-options

**Comment by martinklepsch** [comment]
> https://playwright.dev/docs/api/class-testoptions#test-options-launch-options

That worked like a charm! Thank you so much!
