### ISSUE TITLE
Need a predefined profile for Firefox

### ISSUE THREAD

**Issue by gyurik** [microsoft/playwright-testing-service#80]
Currently Playwright cannot use any predefined browser profile. This makes big problem where the system needs a logon for using the system. It especially problematic on Azure itself with a TFA where the 2nd F is a human action with the MS Authenticator. 

My request is: Playwright should use a preauthenticated profile for Firefox for being able to test such systems where login is mandatory and there is no way to enter the sign in information during an automated test.

With Robot Framework I can use a predefined profile for Firefox and the automation is not a problem with the system, which  requires login at the start of the usage.

AB#1922447

**Comment by puagarwa** [comment]
@gyurik this should go into playwright open source framework repo https://github.com/microsoft/playwright
