### ISSUE TITLE
[BUG]:Wrong tenant selected during login

### ISSUE THREAD

**Issue by wi5nia** [microsoft/playwright-testing-service#83]
**Describe the bug**
When I go to https://playwright.microsoft.com/ and click "Sign in" I use my account: tom...@...ive.com. The problem is that the website want's to use a tenant to which my account is no longer linked to thus I can't login.

When I do the same thing in private mode it works (although it selects the first tenant it can find on the list instead of my default one but at least I get to the Playright portal.

I've already tried cleaning up cookies (multiple times and yes - all cookies) and still nothing.

**To Reproduce**
1. Go to https://playwright.microsoft.com/
2. Click "Sign in"
3. Use account tom...@...ive.com

**Expected behavior**
The login process to finish in the Playright portal preferable with the default tenant selected.

**Screenshots**
<img width="1220" alt="image" src="https://github.com/microsoft/playwright-testing-service/assets/12593852/c730b28b-c437-4abc-bb80-c2951d098337">

<img width="1227" alt="image" src="https://github.com/microsoft/playwright-testing-service/assets/12593852/75dafa1f-bc44-4eaa-8169-bb8f25c65aa1">

**Additional context**
Using Edge on MacOs - all latest versions.

AB#1923149

**Comment by prakash-amit** [comment]
Hi @wi5nia,

Thanks for reporting this issue. 

We wanted some inputs from your side to help figure out exact issue you are facing:
1. Can you confirm if you are able to login and see screen similar to second screen in non-private mode and then you are trying to switch tenant or you are not able to proceed further from account selection window as shown in first screenshot.
2. If login is not successful as I can see in first screenshot, could you open network tab ( **Command+Option+I** and select network tab) before trying login, See if https://management.azure.com/tenants?api-version=2022-09-01 call is made and in response list are you getting the unlinked tenant as first tenant.

Thanks for your support!
cc @vanshisingh

**Comment by vvs11** [comment]
Hi @wi5nia 
Are you still seeing this issue? We have made several updates to improve the experience in this flow. Let us know if this still exists.

**Comment by wi5nia** [comment]
NO, because now the directory switcher in Playwright works like it should :)
