### ISSUE TITLE
[BUG]:browserType.connect: WebSocket error: unable to get local issuer certificate

### ISSUE THREAD

**Issue by JanakiramanPachaiyappan** [microsoft/playwright-testing-service#84]
I get this error when i try to run the test. 

Error: browserType.connect: WebSocket error: unable to get local issuer certificate
    Call log:
      - <ws connecting> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession
      - <ws error> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established
      - <ws connect error> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established
      - <ws disconnected> wss://eastus.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=
      - <ws connecting> wss://browser.playwright-int.io/ws
      - <ws error> wss://browser.playwright-int.io/ws error unable to get local issuer certificate
      - <ws connect error> wss://browser.playwright-int.io/ws unable to get local issuer certificate
      - <ws disconnected> wss://browser.playwright-int.io/ws code=1006 reason=

AB#1924374

**Comment by puagarwa** [comment]
Hi @JanakiramanPachaiyappan There was a regression at our end which was causing domain to go into playwright-int.io instead of playwright.microsoft.com , We have corrected it now, can you give it a try and confirm if its working now.

**Comment by JanakiramanPachaiyappan** [comment]
Thanks. It works fine now.

**Comment by paradix86** [comment]
having today this same issue:
 Error: browserType.connect: WebSocket error: wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized
    Call log:
      - <ws connecting> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession
      - 1a04d19f-4e3a-40b3-bada-b4e52d696993
      - <ws unexpected response> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized
      - <ws error> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established
      - <ws connect error> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established
      - <ws disconnected> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=

**Comment by puagarwa** [comment]
> having today this same issue: Error: browserType.connect: WebSocket error: wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized Call log: - wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession - 1a04d19f-4e3a-40b3-bada-b4e52d696993 - wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized - wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established - wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established - wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=

This is different issue as you are getting 401. Let me respond in detail on seperate issue https://github.com/microsoft/playwright-testing-service/issues/107
