### ISSUE TITLE
Quota increase request

### ISSUE THREAD

**Issue by JanakiramanPachaiyappan** [microsoft/playwright-testing-service#85]
Maximum number of workers for the workspace - 6000

**Business Justification:**

We would like to perform a load test for 6000 users and monitor the performance and get some analytics. 

**Requested New Quota Limit:**

6000 workers.

**Additional Information:**

**Setup Information:**

- **Subscription ID:** 8ff85366-7f6b-4c50-a470-071bbf4ced73
- **Workspace ID:** pwraptortests

**Disclaimer:**

Please note that while we will do our best to accommodate your quota extension request, we may not be able to fulfill every request due to resource constraints. We will review your request and provide a response as soon as possible.

AB#1925493

**Comment by vvs11** [comment]
@JanakiramanPachaiyappan We'd like to understand your scenario better. We can discuss about possible approaches to do this testing. Would it be possible to schedule a meeting to go over this? 
You can write to us at playwrighttesting@microsoft.com to take the conversation forward. 
Thanks

**Comment by vvs11** [comment]
Hi @JanakiramanPachaiyappan , 
Please let us know how we can connect. We want to understand your use-case in more detail and discuss approaches you can use to solve this.

**Comment by JanakiramanPachaiyappan** [comment]
Hi @vvs11, I have sent you email on this. Thanks.

**Comment by vvs11** [comment]
Closing this and taking it forward in offline conversation
