### ISSUE TITLE
[BUG]:Activity log status stuck in "In progress"  when running with +30 workers

### ISSUE THREAD

**Issue by garciallorente-fer** [microsoft/playwright-testing-service#88]
**Describe the bug**
I did the first trials to run the Playwright tests using Microsoft Playwright Testing , the first set of tests using just 2 workers seemed to be worked okay, but as soon as I tried to run the whole test suit that we have, +30 tests, using +30 workers, it run them but it did not showed the information according to the run, and just stopped in : In Progress, and has been like this for more than a week.

**Expected behavior**
To see the number of workers used, time, etc.

**Screenshots**
![image](https://github.com/microsoft/playwright-testing-service/assets/55386160/7be9a48d-0dac-4b61-9be5-c3a395082bb7)

**Setup information (please complete the following information):**
 - Azure Subscription Id: 1c9cad22-2324-4f55-965d-f8609191cfe2
 - Workspace Name: rockpooldevelopmentpwt
 - Service trace Id (if available): 
 - Log snippet (if available): 
 - Browser on which tests are executed (if applicable): chromium
 - Time range (in PST) when the issue was experienced: from 2023-12-08
 - Playwright Version: 1.40.1
- Client machine OS: windows
- OS requested on Service: linux

AB#1930945

**Comment by pratiksharma23** [comment]
Hi @garciallorente-fer, there is an issue on our end in scenarios where runId contains special characters such as '/' (forward slash).  We would be adding handling such such cases in the next update. Meanwhile, to unblock yourself, please try providing the runId without the forward slash.

**Comment by vvs11** [comment]
@garciallorente-fer Is this workaround working for you?

**Comment by garciallorente-fer** [comment]
@pratiksharma23 @vvs11 that works thanks guys!
