### ISSUE TITLE
Quota increase request

### ISSUE THREAD

**Issue by dcaprani** [microsoft/playwright-testing-service#91]
## Quota Increase Request

**Quota to Increase: No. of concurrent workers
 

  

Workspace name        performancetestweijie
Workspace ID              westeurope_8892ff40-65cb-4596-8b0d-d062cf2802b2 
Subscription                IAM-DEV
Subscription ID            59627062-b4a8-48db-a951-c71c06a2e401 
 
]

* [1,000] Maximum number of workers for the workspace
* [2] Maximum number of workspaces per subscription
* [ ] Throttling limits
* [ ] Other

 

**Business Justification:**

[We need to increase the concurrent users for our performance tests, the current setting of 50 is too low to reflect our expected peak usage.]

**Requested New Quota Limit:**

[We are requesting a quota limit of 1,000 concurrent users as this more accurately reflects our expected peak usage.  Our current setting of 2 workspaces per subscription is sufficient for now.]

**Additional Information:**

[Include any additional information that may be relevant to your request, such as project deadlines, the impact of the quota increase on your work, etc.]

**Setup Information:**

Workspace name        performancetestweijie
Workspace ID              westeurope_8892ff40-65cb-4596-8b0d-d062cf2802b2 
Subscription                IAM-DEV
Subscription ID            59627062-b4a8-48db-a951-c71c06a2e401 

**Disclaimer:**

Please note that while we will do our best to accommodate your quota extension request, we may not be able to fulfill every request due to resource constraints. We will review your request and provide a response as soon as possible.

AB#1939895

**Comment by vvs11** [comment]
Hi @dcaprani 
Thanks for writing to us. 
I'd like to understand your scenario better. Would it be possible to set up a quick call and discuss this? Please let me know how we can meet or you can send us an email at playwrighttesting@microsoft.com and we can take the discussion forward. 
Thanks

**Comment by dcaprani** [comment]
Hi @vvs11
I sent you an email requesting a meeting, we're very keen to do so as we'd like to resolve this as soon as we can.  When would suit you to meet? 
Regards
Derek

**Comment by vvs11** [comment]
HI @dcaprani
I have sent you an invite. Please let me know if the time is not suitable for you and your team. Looking forward to meeting you soon. 

Thanks

**Comment by vvs11** [comment]
As per our discussion, closing this request. Feel free to re-open if you have any issues.
