### ISSUE TITLE
[BUG]:Error: browserType.connect: WebSocket error: wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized

### ISSUE THREAD

**Issue by AlanCodega** [microsoft/playwright-testing-service#96]
**Describe the bug**
Since yesterday we've having this error with EVERY spec file we run:

Error: browserType.connect: WebSocket error: wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized
Call log:
  - <ws connecting> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession
  - 86ea1997-8795-42e1-9067-41b045914491
  - <ws unexpected response> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession 401 Unauthorized
  - <ws error> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession error WebSocket was closed before the connection was established
  - <ws connect error> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession WebSocket was closed before the connection was established
  - <ws disconnected> wss://westeurope.api.playwright.microsoft.com/api/authorize/connectSession code=1006 reason=

**To Reproduce**
run any playwright test with vscode

**Expected behavior**
not having this "generic" error

**Screenshots**
![image](https://github.com/microsoft/playwright-testing-service/assets/124665156/b2ed30d9-3623-43aa-b7e2-1243aabb3fb3)

**Setup information (please complete the following information):**

 - Browser on which tests are executed (if applicable): Chrome
 - Playwright Version: 14.1
- Client machine OS: WIndows 11

AB#1952828

**Comment by vvs11** [comment]
Hi @AlanCodega 
Thanks for reaching out. This error could be because the Access Token you were using to authenticate with the service is expired or not set for this run. 
Could you check if the token is active and create a new token if it's expired? Here's the documentation: https://learn.microsoft.com/en-us/azure/playwright-testing/how-to-manage-access-tokens

**Comment by AlanCodega** [comment]
> Hi @AlanCodega Thanks for reaching out. This error could be because the Access Token you were using to authenticate with the service is expired or not set for this run. Could you check if the token is active and create a new token if it's expired? Here's the documentation: https://learn.microsoft.com/en-us/azure/playwright-testing/how-to-manage-access-tokens

Hi @vvs11 ,
many thanks for your reply.

it's the 1st thing I thought.
I've re-create the token following this guide:
![image](https://github.com/microsoft/playwright-testing-service/assets/124665156/8598042d-5960-431c-91d2-d33a2d2cd272)


But still have the same issue, even if I want to run locally:
![image](https://github.com/microsoft/playwright-testing-service/assets/124665156/6a0e19f5-f77f-4367-a572-52f547a55e1e)

**Comment by puagarwa** [comment]
HI @AlanCodega We checked our telemetry and it shows that token you are using is expired, one possibility is though you have generated new token but you havent updated it your system to pick new token value.  Can you please check your environment variable once. You can actually check the token validatity via jwt.io , please confirm after this.

**Comment by AlanCodega** [comment]
> HI @AlanCodega We checked our telemetry and it shows that token you are using is expired, one possibility is though you have generated new token but you havent updated it your system to pick new token value. Can you please check your environment variable once. You can actually check the token validatity via jwt.io , please confirm after this.

Hi @puagarwa,
Many thanks for your reply.

i found the issue, and you have reason.

I updated the token following the guide using powershell commands, but we had an .env fine in our vs code.
Once I've updated the token here, everything was run as before.

Many thanks for your help.
